Implemented: Support to store user preference for selected product store(#2f2h8hu)
hotwax/inventory-count pull request #100
Opened 2022-08-30 12:05 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2022-10-06 07:35 UTC, disha1202 requested changes
Pass token while dispatching getProfile.
https://github.com/hotwax/inventory-count/blob/main/src/store/modules/user/actions.ts#L36

https://github.com/hotwax/inventory-count/blob/main/src/store/modules/user/actions.ts#L50

2022-10-06 07:35 UTC, disha1202 commented on src/store/modules/user/actions.ts
> +          console.log(err)
```suggestion
          console.error(err)
```

2022-10-06 08:00 UTC, disha1202 requested changes

2022-10-06 08:00 UTC, disha1202 commented on src/store/modules/user/actions.ts
>        commit(types.USER_CURRENT_FACILITY_UPDATED, resp.data.facilities.length > 0 ? resp.data.facilities[0] : {});
```suggestion
      dispatch("setFacility", { facility: resp.data.facilities[0] });
```

2022-10-07 06:22 UTC, shashwatbangar commented on src/store/modules/user/actions.ts
> +          console.log(err)
Done

2022-10-07 06:22 UTC, shashwatbangar commented on src/store/modules/user/actions.ts
>        commit(types.USER_CURRENT_FACILITY_UPDATED, resp.data.facilities.length > 0 ? resp.data.facilities[0] : {});
Done

2023-02-02 12:38 UTC, dt2patel commented
not using product store in inventory count app. closing PR

2023-02-02 12:38 UTC, closed without merging