Updated the code to navigate to the product page after scanning(#1z59ah8)
hotwax/inventory-count pull request #117
Opened 2022-11-10 11:10 UTC by k2maan

### Related Issues

Closes #113

### Short Description and Why It's Useful

For a better UX, the search bar and the searched product list will be cleared after the successful scan of an SKU.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2022-11-10 12:53 UTC, ymaheshwari1 requested changes

2022-11-10 12:53 UTC, ymaheshwari1 commented on changelogs/unreleased/-1z59ah8.yml
> +---
Remove changelog entry file

2022-11-10 12:53 UTC, ymaheshwari1 commented on src/views/Search.vue
> +            this.queryString = '';
We can instead just don't assign a value to `this.queryString` on line 104.

2022-11-18 13:14 UTC, adityasharma7 requested changes

2022-11-18 13:14 UTC, adityasharma7 commented on src/views/Search.vue
> +            this.queryString = '';
I think this needs to do differently, we tried to use the existing method which is quite good, but as the flow works differently we should have a new implementation for the scanning and query search.

2022-12-05 05:35 UTC, ymaheshwari1 commented
Dependent on #56

2023-02-02 12:34 UTC, closed without merging

2023-02-02 12:34 UTC, disha1202 commented
Not needed, closing