Implemented: Updated UI of Settings page(#32j3r6t)
hotwax/inventory-count pull request #123
Opened 2022-12-07 05:57 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

![Screenshot 2022-12-07 at 11 25 22 AM](https://user-images.githubusercontent.com/62360781/206100101-63b1c6fa-fe15-40e8-bf7a-d21f9b6412fc.png)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2023-01-10 05:37 UTC, k2maan commented on src/views/Settings.vue
> +  }
Fix indentation

2023-01-10 05:46 UTC, k2maan approved these changes

2023-01-10 05:47 UTC, shashwatbangar commented on src/views/Settings.vue
> +  }
Done sir

2023-01-11 12:53 UTC, adityasharma7 requested changes

2023-01-11 12:53 UTC, adityasharma7 commented on src/views/Settings.vue
> +            <ion-card-subtitle>
I think this is not needed in this app

2023-01-12 06:42 UTC, shashwatbangar commented on src/views/Settings.vue
> +            <ion-card-subtitle>
ok sir

2023-01-12 07:04 UTC, ymaheshwari1 commented on src/views/Settings.vue
> +            <ion-card-subtitle>
We need this section to let user select facilities, but we need to change the title, subtitle and description as per `facilties`

2023-01-17 09:45 UTC, merged