Added support to scan products with all the product identifications(#85zrjbtxf)
hotwax/inventory-count pull request #140
Opened 2023-01-17 09:22 UTC by disha1202

### Related Issues

Closes #138 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2023-01-19 09:57 UTC, k2maan approved these changes

2023-01-20 09:15 UTC, adityasharma7 approved these changes

2023-01-20 12:27 UTC, adityasharma7 requested changes

2023-01-20 12:27 UTC, adityasharma7 commented on src/store/modules/product/actions.ts
> -        "filters": ['sku: ' + payload.queryString, 'isVirtual: false'],
I think we could ORing in filters

2023-01-27 11:57 UTC, dt2patel commented
Closing, handled in: #146

2023-01-27 11:57 UTC, closed without merging