Updated code to disable the upload button when no products to upload (#85zrjcac7)
hotwax/inventory-count pull request #142
Opened 2023-01-17 11:21 UTC by k2maan

### Related Issues

Closes #104 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2023-01-18 11:21 UTC, shashwatbangar approved these changes
Verified workflow. Working fine.

2023-01-20 10:13 UTC, ymaheshwari1 requested changes

2023-01-20 10:13 UTC, ymaheshwari1 commented on src/views/Upload.vue
> +        <ion-fab-button @click="upload()" :disabled="Object.keys(uploadProducts).length === 0">
As we have added the length check here, we can remove the same check from the `upload` method.

2023-01-20 10:20 UTC, ymaheshwari1 approved these changes

2023-01-20 12:24 UTC, merged