Fixed: Product data not fetched on refresh (#85zrvh9we)
hotwax/inventory-count pull request #167
Opened 2023-04-05 06:49 UTC by k2maan

### Related Issues

Closes #165 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

[Screencast from 05-04-23 12:17:57 PM IST.webm](https://user-images.githubusercontent.com/59442907/230002591-72b3c157-1eaf-479a-8d78-db9747a41eb4.webm)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2023-04-05 06:56 UTC, ymaheshwari1 requested changes

2023-04-05 06:56 UTC, ymaheshwari1 commented on src/App.vue
>          unauthorised: this.unauthorized,
```suggestion
        unauthorised: this.unauthorised,
```

2023-04-05 09:04 UTC, k2maan commented on src/App.vue
>          unauthorised: this.unauthorized,
Updated sir

2023-04-05 09:08 UTC, ymaheshwari1 approved these changes

2023-04-06 09:17 UTC, adityasharma7 approved these changes

2023-04-06 09:17 UTC, merged