Implemented: empty state in search page(#201)
hotwax/inventory-count pull request #203
Opened 2023-09-19 13:29 UTC by tanishqueSharma

### Related Issues

Closes #201

### Short Description and Why It's Useful

Implemented: Empty state in search page.

### Screenshots of Visual Changes before/after (If There Are Any)

Before
![Screenshot (28)](https://github.com/hotwax/inventory-count/assets/142586530/5045622e-710d-4b62-9e72-f52d0c56aeac)

After
![Screenshot (29)](https://github.com/hotwax/inventory-count/assets/142586530/50aeec3e-c04e-4842-ac30-625119a5cd24)

### Contribution and Currently Important Rules Acceptance

- [x] I have read and followed [contribution rules](https://github.com/hotwax/inventory-count#contribution-guideline)

2023-09-20 05:05 UTC, sanskar345 commented on src/views/Search.vue
> +        <p v-if="products.length===0">{{ $t("No results found")}}</p>
v-if="products.length===0" is not required here, it is already in div with the condition. And improve the logic of displaying the "No results found" message. It should be diplayed only when the user searches for a product not initially.

2023-09-20 05:06 UTC, sanskar345 commented on src/store/modules/product/actions.ts
> +
Remove the extra line

2023-09-20 07:28 UTC, sanskar345 commented on src/views/Search.vue
> +        this.fetchingProduct = false;
No need assignment to fetchingProduct here it should be in searchProducts func

2023-09-20 07:29 UTC, sanskar345 commented on src/views/Search.vue
> +        this.showErrorMessage = true;
No need of this assignment to var

2023-09-20 09:05 UTC, sanskar345 approved these changes

2023-09-20 09:41 UTC, k2maan approved these changes

2023-09-21 05:07 UTC, ymaheshwari1 requested changes

2023-09-21 05:07 UTC, ymaheshwari1 commented on src/store/modules/product/actions.ts
> -        showToast(translate("Product not found"));
Remove this entry from the locale file as well, if not used anywhere else.

2023-09-21 06:05 UTC, ymaheshwari1 approved these changes

2023-10-11 05:19 UTC, merged