Improved: Added Toast Notification on Item Removal from Upload Page(#213)
hotwax/inventory-count pull request #224
Opened 2023-12-06 10:37 UTC by shanmukhdutt

(#213 )
### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [ ] I have read and followed [contribution rules](https://github.com/hotwax/inventory-count#contribution-guideline)

2023-12-12 09:29 UTC, k2maan approved these changes

2023-12-20 10:52 UTC, amansinghbais commented on src/store/modules/product/actions.ts
> +    showToast(translate("Item removed successfully"));
Show this toast from the upload page post action call in remove item function.

2023-12-20 13:25 UTC, amansinghbais commented on src/locales/en.json
> +
remove unwanted new line

2023-12-27 09:41 UTC, ymaheshwari1 requested changes

2023-12-27 09:41 UTC, ymaheshwari1 commented on src/views/Upload.vue
> +      showToast(this.$t("Item removed successfully"));
```suggestion
      showToast(this.$t("Item removed from upload list"));
```

2024-01-03 06:05 UTC, ymaheshwari1 requested changes

2024-01-03 06:05 UTC, ymaheshwari1 commented on src/locales/en.json
> +  "Item removed successfully":"Item removed successfully",
Update the translation as this text is changed to `Item removed from upload list`

2024-01-03 06:33 UTC, ymaheshwari1 approved these changes

2024-01-03 06:34 UTC, merged