Fixed: Enabled Everywhere on the card Open Detail Page on Upload Page (#209)
hotwax/inventory-count pull request #225
Opened 2023-12-07 04:59 UTC by shanmukhdutt

#209

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [ ] I have read and followed [contribution rules](https://github.com/hotwax/inventory-count#contribution-guideline)

2023-12-12 09:30 UTC, k2maan approved these changes

2023-12-27 09:42 UTC, ymaheshwari1 approved these changes

2024-02-08 13:44 UTC, ymaheshwari1 requested changes

2024-02-08 13:44 UTC, ymaheshwari1 commented on src/views/Upload.vue
> +      <ion-card v-for="product in uploadProducts" :key="product.productId" @click="viewProduct(product)">
Remove the click event from ion-label, as we have added the event on the card itself.

2024-02-09 04:14 UTC, ymaheshwari1 approved these changes

2024-02-09 04:17 UTC, merged