Fixed: Prevented Updating Negative Inventory Counts
hotwax/inventory-count pull request #228
Opened 2023-12-08 05:53 UTC by shanmukhdutt

(#207)

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [ ] I have read and followed [contribution rules](https://github.com/hotwax/inventory-count#contribution-guideline)

2023-12-12 09:31 UTC, k2maan requested changes

2023-12-12 09:31 UTC, k2maan commented on src/views/count.vue
> +        }else{
Improve spacing here

2023-12-12 09:31 UTC, k2maan commented on src/locales/en.json
> +  "Neagative stock count cannot be accepted":"Neagative stock count cannot be accepted",
Please recheck the spellings

2023-12-20 10:56 UTC, amansinghbais commented on src/views/count.vue
> +        if (this.quantity > 0) {
if(this.quantity > 0) {

2023-12-20 10:58 UTC, amansinghbais commented on src/views/count.vue
> +        if (this.quantity > 0) {
```suggestion
        if(this.quantity > 0) {
```

2023-12-20 11:01 UTC, amansinghbais commented on src/locales/en.json
> +  "Negative stock count cannot be accepted":"Negative stock count cannot be accepted",
```suggestion
  "Negative stock count cannot be accepted": "Negative stock count cannot be accepted",
```

2023-12-27 09:44 UTC, ymaheshwari1 requested changes

2023-12-27 09:44 UTC, ymaheshwari1 commented on src/views/count.vue
> +        if(this.quantity) {
We have not handled negative check in this case, and also we have added static text entry in locale but have added the toast anywhere

2024-04-26 07:22 UTC, ymaheshwari1 commented
Closing as having conflicts and needs improvements.

2024-04-26 07:22 UTC, closed without merging