Implemented: Spinner in Timezone Model for Timezone Configuration (#210)
hotwax/inventory-count pull request #249
Opened 2024-01-06 04:20 UTC by Ritika-Patel08

### Related Issues

Closes #210

### Short Description and Why It's Useful

Spinner is added to show that the timezones are being fetched from the API. It is indicating to the user that the data is loading.

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Import
![Screenshot 2024-01-06 093850](https://github.com/hotwax/inventory-count/assets/83332530/348205af-8a58-4280-81f0-4ef0d4f035c7)
ant Rules Acceptance

- [x] I have read and followed [contribution rules](https://github.com/hotwax/inventory-count#contribution-guideline)

2024-01-06 04:51 UTC, ymaheshwari1 requested changes

2024-01-06 04:51 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> + import { defineComponent } from "vue";
Remove all the irrelevant changes from the PR those are not related to the issue, like adding extra lines, changing single-quotes to double quotes and vice-versa, changing indentation, adding space after keywords.

2024-01-06 04:51 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> +            }})</ion-radio>
Unwanted change, please revert.

2024-01-06 04:51 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> +      <div class="empty-state">
No need to have extra div for adding if condition, adding a class and if condition can be handled in a single div.

2024-01-06 04:51 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> +          <ion-spinner class="center-spinner" color="secondary" name="crescent" slot="start" ></ion-spinner>
Class `center-spinner` is unused.

2024-01-06 04:51 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> +      console.log(resp);
Remove console statement from the code, as we use this console statements for debugging hence should not be pushed.

2024-01-08 07:06 UTC, amansinghbais commented on src/locales/en.json
> +  "Fetching time zones":"Fetching time zones",
```suggestion
  "Fetching time zones": "Fetching time zones",
```

2024-01-08 07:06 UTC, amansinghbais commented on src/views/TimezoneModal.vue
> +      <ion-item lines="none" >
```suggestion
      <ion-item lines="none">
```

2024-01-08 07:06 UTC, amansinghbais commented on src/views/TimezoneModal.vue
> +        <ion-spinner color="secondary" name="crescent" slot="start" ></ion-spinner>
Use self closing tag instead.

2024-01-09 06:15 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> +    this.isLoading = false;
Improve identation.

2024-01-09 06:23 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> +      isLoading: true
We can change `isLoading` to false initially and make it true when the timeZone search method is called.
Because if in some case we change the code and stop calling the search method on mount then as here the `isLoading` will be true, the loader will always load indefinitely.

Also, in current case when searching for timeZone the loader does not work, if not initializing the `isLoading` to true in the method.

2024-01-10 06:01 UTC, ymaheshwari1 approved these changes

2024-01-10 07:17 UTC, merged