Updated the code to navigate to the product page after scanning(#1z59ah8)
hotwax/inventory-count pull request #56
Opened 2022-01-24 11:29 UTC by disha1202

…ah8)

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2022-04-06 11:56 UTC, meet-aniket requested changes

2022-04-06 11:56 UTC, meet-aniket commented on src/views/Search.vue
>            if(result.role){
Here, if we are clicking out of the camera modal we will get an error here try to handle this condition like this:- `result.role && result.role !== 'backdrop'`.

2022-05-17 09:55 UTC, meet-aniket approved these changes

2023-02-02 12:36 UTC, dt2patel commented
Not part of plan anymore, closing PR

2023-02-02 12:36 UTC, closed without merging