Implemented functionality to add support to select eComStore from the settings page (#251xhvt).
hotwax/inventory-count pull request #80
Opened 2022-04-04 11:28 UTC by meet-aniket

2022-04-06 05:30 UTC, adityasharma7 requested changes

2022-04-06 05:30 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +      await dispatch('getEComStores', { facilityId: resp.data.facilities[0] })
Handle the case if no facilities list is available

2022-04-07 12:37 UTC, ymaheshwari1 requested changes

2022-04-07 12:37 UTC, ymaheshwari1 commented on src/store/modules/user/actions.ts
> +    return resp.data
Here we don't always have resp.data, instead we should just return resp.

2023-02-02 12:37 UTC, dt2patel commented
Don't need this PR, closing

2023-02-02 12:37 UTC, closed without merging