Users should be directly able to navigate to the product detail page (#1yzcv99)
hotwax/inventory-count pull request #87
Opened 2022-05-27 11:14 UTC by rathoreprashant

### Related Issues
Improved: code handled fetchProducts by catch

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

2022-05-27 11:24 UTC, ymaheshwari1 requested changes

2022-05-27 11:24 UTC, ymaheshwari1 commented on src/store/modules/product/actions.ts
> +        commit(types.PRODUCT_CURRENT_UPDATED, { product: resp.data.response.docs[0] })
Handle the case when we have a response, but the status of the response is not 200, or the response contains error field, or the response has empty data.

2022-05-27 11:24 UTC, ymaheshwari1 requested changes

2022-05-27 11:24 UTC, ymaheshwari1 commented on src/store/modules/product/actions.ts
> +        console.log(error);
Make it console.error

2022-05-27 11:25 UTC, rathoreprashant commented on src/store/modules/product/actions.ts
> +        console.log(error);
ok sir

2022-05-27 12:54 UTC, rathoreprashant commented on src/store/modules/product/actions.ts
> +        console.log(error);
Improved sir

2022-05-27 13:27 UTC, ymaheshwari1 requested changes

2022-05-27 13:27 UTC, ymaheshwari1 commented on src/store/modules/product/actions.ts
> +      if (resp.status === 200 && resp.data.response?.numFound > 0 && !hasError(resp)) {
```suggestion
      if (resp.status === 200 && resp.data?.response?.numFound > 0 && !hasError(resp)) {
```

2022-05-27 13:27 UTC, ymaheshwari1 commented on src/store/modules/product/actions.ts
> +          commit(types.PRODUCT_CURRENT_UPDATED, { product: resp.data.response.docs[0] })
Improve indentation

2022-05-27 13:28 UTC, rathoreprashant commented on src/store/modules/product/actions.ts
> +          commit(types.PRODUCT_CURRENT_UPDATED, { product: resp.data.response.docs[0] })
ok sir

2022-05-27 13:44 UTC, rathoreprashant commented on src/store/modules/product/actions.ts
> +          commit(types.PRODUCT_CURRENT_UPDATED, { product: resp.data.response.docs[0] })
Fixed Sir

2022-05-27 13:44 UTC, rathoreprashant commented on src/store/modules/product/actions.ts
> +      if (resp.status === 200 && resp.data.response?.numFound > 0 && !hasError(resp)) {
Updated sir

2023-02-02 12:38 UTC, disha1202 commented
Not needed, closing.

2023-02-02 12:38 UTC, closed without merging